### ISSUE TITLE
新版arm芯片的Mac系统有问题

### ISSUE THREAD

**Issue by keel** [seanliang/Codecs33#8]
打印了下异常:

`dlopen(/Users/...../Library/Application Support/Sublime Text/Packages/Codecs33/lib/_multibytecodec.so, 0x0002): tried: '/Users/....../Library/Application Support/Sublime Text/Packages/Codecs33/lib/_multibytecodec.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_multibytecodec.so' (no such file)`

**Comment by seanliang** [comment]
目前暂无法提供这个包的arm版本，建议升级到Sublime Text 4，不再依赖这个包，即可删除。

**Comment by keel** [comment]
是的， 新版emmet不再需要这个库了， 多谢回复.
